### ISSUE TITLE
error: vercel 빌드 중 발생한 오류

### ISSUE THREAD

**Issue by kimsudang** [passion-mansour/passion-mansour-teambeam-frontend#15]
![image](https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/143993211/17c6a61b-2ebe-483e-9e86-3cf569dbfaea)

**Comment by gkdud3579** [comment]
## 원인
error가 unknown 타입으로 지정되어 있어서 발생하는 오류
## 해결방안
error가 AxiosError 인스턴스인지 확인하고, 그렇다면 response 데이터를 콘솔에 출력하고, 그렇지 않다면 일반적인 error 메시지를 출력하도록 수정

**Comment by kimsudang** [comment]
![image](https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/143993211/cd5f5afa-540f-4f42-87ba-f65af4218536)

새로운 오류입니다!

**Comment by gkdud3579** [comment]
## 원인
1. 타입 불일치: TypeScript에서 타입 불일치 문제가 발생했습니다. 특히 member 속성이 TodoItem 타입에 정의되지 않았는데, 코드에서 lowerTodo 객체에 추가되면서 문제가 발생했습니다.
2. 부모-자식 관계 설정 문제: 하위 투두를 추가할 때 상위 투두와 중위 투두의 ID를 설정하지 않거나 잘못 설정하는 문제가 있었습니다.
Omit 사용: Omit을 사용해 불필요한 속성을 제외하면서도 올바른 속성을 포함해야 했습니다.
## 해결방안
1. member 속성 제거: lowerTodo 객체에서 member 속성을 제거하고, API 호출 시에만 추가하도록 수정했습니다. 이는 TodoItem 타입에 맞게 객체를 정의하는 데 도움을 줍니다.
2. 부모-자식 관계 설정: 하위 투두를 추가할 때 middleTodoId와 topTodoId를 명확히 설정했습니다. 이는 상태 업데이트 시 올바른 부모-자식 관계를 유지하도록 합니다.
