### ISSUE TITLE
Vercel 배포 관련 이슈

### ISSUE THREAD

**Issue by kimsudang** [passion-mansour/passion-mansour-teambeam-frontend#4]
Vercel에서 무료 플랜을 위해 포크한 repo를 빌드하던 중에 발생한 오류입니다.

![스크린샷 2024-05-21 120711](https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/143993211/8a8a3cd7-853f-43a5-9a51-cc5f84c4e675)

**Comment by gkdud3579** [comment]
## 이슈 원인 
TodoItem 타입에 subtasks 속성이 정의되지 않아서 발생

## 해결 방안
1. subtasks 속성을 TodoItem 타입에 추가하고, subtask와 index 파라미터에 타입을 명시

```
export interface TodoItem {
  id: string;
  title: string;
  startDate: string;
  endDate: string;
  assignees?: string[];
  subtasks?: TodoItem[]; // subtasks 속성 추가
}
```
2. MiddleTodoList 컴포넌트에서 subtask와 index 파라미터에 타입을 명시하고, subtasks 속성을 사용하도록 수정
