### ISSUE TITLE
ERROR: 크램폴린 빌드 시 오류 발생

### ISSUE THREAD

**Issue by bakseungho** [passion-mansour/passion-mansour-teambeam-frontend#53]
<img width="1122" alt="스크린샷 2024-06-11 오전 3 42 03" src="https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/37357863/604fba3d-4070-4569-ad9f-2ecb6ddf557f">

해당 모듈을 찾을 수 없다고 나와있는데 확인 결과 ../main/types 파일이 없는 것 같습니다.

@gkdud3579  확인 부탁드리겠습니다!

**Comment by gkdud3579** [comment]
이 이슈탭 발생한 오류부분 읽어봤는데요,
컴포넌트명이 개인페이지쪽이라서 제가 작성한 코드부분이 아닌것같습니다! 혹시 확인가능할까요? @kimsudang

**Comment by kimsudang** [comment]
네 제 부분에서 작성된 코드입니다! 현재 해당 페이지 기능 개발 중이라 함께 푸시하고 말씀드릴게요 @bakseungho

**Comment by kimsudang** [comment]
@bakseungho  수정된 코드로 푸시 했습니다! 다시 한 번 확인 부탁드립니다 :)

**Comment by bakseungho** [comment]
<img width="1069" alt="스크린샷 2024-06-11 오후 8 51 13" src="https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/37357863/48c00615-1188-4569-9fa3-95a3b018803a">


<img width="1038" alt="스크린샷 2024-06-11 오후 8 51 00" src="https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/37357863/026c262f-7ff7-4acb-b404-e3b3e79acdbf">


@kimsudang  수연님 /user/settingPassword , /user/join 쪽에서 오류 2건이 발생 했는데 확인 부탁드리겠습니다!

**Comment by kimsudang** [comment]
@bakseungho 승호님 우선 제가 아는 선에서 프리렌더링 이슈를 수정해서 다시 푸시했습니다! 확인 부탁드립니다.

**Comment by bakseungho** [comment]
<img width="1041" alt="스크린샷 2024-06-13 오전 11 53 59" src="https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/37357863/95ae8c9b-2284-4e0c-ba9d-6062a038ca73">

@gkdud3579 하영님 여기 부분 타입오류 있어서 빌드 실패 되었습니다. 확인 부탁드립니다

**Comment by gkdud3579** [comment]
@bakseungho 수정 후, 배포 완료했습니다
## 수정사항
1. fetchParticipants 함수 정의를 수정해서 필요한 모든 매개변수를 받을 수 있도록 수정
2. tagId 파라미터의 타입을 명시적으로 지정

**Comment by bakseungho** [comment]
<img width="1111" alt="스크린샷 2024-06-17 오후 10 23 21" src="https://github.com/passion-mansour/passion-mansour-teambeam-frontend/assets/37357863/cc34344c-53a4-4c20-98ef-696b277c2c67">

@kimsudang teamSetting 부분 오류가 발생했습니다 확인 부탁드릴게요
